### ISSUE TITLE
Cannot sign in as a new user

### ISSUE THREAD

**Issue by jeffryhartanto** [jadenwjh/CS2102_2021_S1_Team45#6]
Hi,

I'm CS2102 TA, I created an account and tried to sign in to the application, but it keeps loading. Any comment on this?

Let me know if you want to resolve this through Zoom meeting.

@jadenwjh @vanessatlx @bscrow @Huisquare

**Comment by bscrow** [comment]
Hi @jeffryhartanto I have just tried the app and I couldn't reproduce the error. Can you share an example of your attempt or perhaps share the userid and password that you have tried? Thanks!

**Comment by jeffryhartanto** [comment]
@bscrow I just created a pet-owner account with username test and password test. Upon log in, the app keeps loading.

![image](https://user-images.githubusercontent.com/7631199/100972868-7b893480-3574-11eb-90ce-303ed60968a8.png)

**Comment by jeffryhartanto** [comment]
@bscrow I just created a pet-owner account with username `test` and password `test`. Upon login, the app just keeps loading (shown below) and nothing happened once it stopped loading.

![image](https://user-images.githubusercontent.com/7631199/100973144-f81c1300-3574-11eb-8225-b2cb64ec4df1.png)

**Comment by bscrow** [comment]
Hi it seems that the sign up isn't successful somehow, as I can't find the username 'test' in the database. Maybe you can try signing up again?

**Comment by jeffryhartanto** [comment]
Is it possible that the account wasn't created? because I don't see any error message.

**Comment by jeffryhartanto** [comment]
@bscrow any constraint on the input fields? There wasn't any error message.

**Comment by bscrow** [comment]
@jeffryhartanto  maybe it will be easier if we settle this on zoom?

**Comment by bscrow** [comment]
The contraint is that all the fields in the registration field must be filled with something, and that the username is not taken. If registration is successful, there should be a popup message at the bottom of the screen saying that registration was successful

**Comment by bscrow** [comment]
I was able to create and then delete the `test` petowner account in your example by following these constraints. I've just deleted the account I created. Perhaps you can try again?

**Comment by jeffryhartanto** [comment]
Got it. I don't know what happened. My guess is that I violated the column constraints of either phone or CC number. Thanks!

**Comment by jeffryhartanto** [comment]
@bscrow Hi, can you share with me the username and password of Caretaker Schwaiger?

I can't create a caretaker account, I don't know what's the problem. Maybe you can share an example values of the input fields for creating a new Caretaker account.

**Comment by bscrow** [comment]
Caretakers additionally must enter one of the current admins as their referral, as explained in the video. This admin will become the "manager" of the caretaker, based on our design. Currently, the 2 admin accounts in the database are "McKirton" and "Trevear". (without "")
Password for Schwaiger is Goldenrod

**Comment by jeffryhartanto** [comment]
Yes, I noticed about the need for referral. But, somehow I still can't login after putting McKirton as the manager. I can't get the account below registered succesfully. Is there any constraint you put on the front end on the fields?

![image](https://user-images.githubusercontent.com/7631199/100985077-7f25b700-3586-11eb-8ea6-7efc3b431218.png)

**Comment by bscrow** [comment]
Ok I think the issue is caused by the phone number. We assumed phone numbers will be at most 8 digits long so it is stored as an int. 12312321312 is outside of the range for int.

**Comment by bscrow** [comment]
![image](https://user-images.githubusercontent.com/38070760/100985923-800b1880-3587-11eb-8905-7b6187fc80f9.png)
Here's a working example - password is pika

**Comment by jeffryhartanto** [comment]
Ah I see. You're right. It works.

Thanks. That's all my question.
